# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: gh-creds
#   namespace: crossplane-system
# type: Opaque
# stringData:
#   token: <token>

---
apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: provider-github
spec:
  package: "glrf/provider-github:v2"

---
apiVersion: github.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gh-creds
      key: token
