# ---
# apiVersion: pkg.crossplane.io/v1beta1
# kind: Provider
# metadata:
#   name: provider-gitlab
# spec:
#   package: "kidswiss/provider-gitlab:latest"

---

apiVersion: v1
kind: Secret
metadata:
  name: gitlab-credentials
stringData:
  token: xKDUsgzwiwM_1EPEWDMR

---
# Gitlab provider that references the secret credentials
apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gitlab-provider
spec:
  baseURL: http://192.168.5.195:8081/
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gitlab-credentials
      key: token
