---

apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group
spec:
  forProvider:
    path: "example-path"
    description: "example description"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system

---

apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: GroupMember
metadata:
  name: example-group-member
spec:
  forProvider:
    groupID: 5
    userID: 2
    accessLevel: 50
    # expiresAt: "2021-06-09"
  providerConfigRef:
    name: gitlab-provider
  writeConnectionSecretToRef:
    name: gitlab-group-example-groupmember
    namespace: crossplane-system

---

apiVersion: projects.gitlab.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
spec:
  forProvider:
    namespaceId: 5
    description: "an example project"
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-project-example-project
    namespace: crossplane-system
